version: '3'

services:
  faktory:
    image: contribsys/faktory
    ports:
      - "7420:7420"
      - "7419:7419"

  ruby-app:
    build: ./ruby-app
    command: bundle exec faktory-worker -q ruby-app -r ./main.rb
    environment:
      - FAKTORY_URL=tcp://faktory:7419
    volumes:
      - ./ruby-app:/usr/src/app
    depends_on:
      - faktory

  node-app:
    build: ./node-app
    command: node main.js
    environment:
      - FAKTORY_URL=tcp://faktory:7419
    volumes:
      - ./node-app:/usr/src/app
    depends_on:
      - faktory
